users: 100
sales: 100
employees: 100
departments: 10
teams: 10
orders: 100
customers: 10
books: 100
authors: 10
courses: 100
students: 10
transactions: 100
student_grades: 100
student_scores: 100
responses: 100
sales_reps: 100
movies: 100
purchases: 100
products: 100
projects: 100
salaries: 100
product_prices: 100
order_statuses: 100
project_stages: 100
daily_sales: 100
user_visits: 100
monthly_sales: 100
customer_orders: 100
product_revenue: 100
employee_sales: 100
employee_projects: 100
employee_performance: 100
